name: Debian stable package

on:
  push:
    branches: []
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: debian:stable

    steps:
    - uses: actions/checkout@v3
      with:
        path: pyhss

    - name: Install dependencies
      run: apt build-dep pyhss

    - name: Build the package
      run: cd pyhss && dpkg-buildpackage --no-sign

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: "*.deb"
